### PR TITLE
#189 add `average_build_mttr` into QoS

### LINKED ISSUE #189: `average_mttr`
Let's add `average_mttr` metric to the `quality-of-service.rb` script. It should calculate the average time (in seconds) between a failed workflow run and a successful one, of the same workflow.

### PR DESCRIPTION
**Pull request by Suban05**
Closes #189

### CODE REVIEW

**Comment by Suban05** [comment]
@Yegorov @tank-bohr please review

File: judges/quality-of-service/quality-of-service.rb [hunk 1]
```diff
@@ -32,15 +32,26 @@
   total = 0
   success = 0
   duration = 0
+  mttr = {}
   Fbe.unmask_repos.each do |repo|
     Fbe.octo.repository_workflow_runs(repo, created: ">#{f.since.utc.iso8601[0..9]}")[:workflow_runs].each do |json|
+      workflow_id = json[:workflow_id]
+      if json[:conclusion] == 'failure'
+        mttr[workflow_id] = { last_failed_at: json[:updated_at] }
```
Comment (Yegorov) [inline judges/quality-of-service/quality-of-service.rb:40]: @Suban05 Why you use `updated_at`? This is exactly the end time of the completion workflow run?

File: judges/quality-of-service/quality-of-service.rb [hunk 2]
```diff
@@ -32,15 +32,26 @@
...
+      elsif json[:conclusion] == 'success' && mttr[workflow_id] && mttr[workflow_id][:last_failed_at]
```
Comment (Yegorov) [inline judges/quality-of-service/quality-of-service.rb:41]: @Suban05 maybe it’s easier to write it like that
```ruby
elsif json[:conclusion] == 'success' && mttr.dig(workflow_id, :last_failed_at)
```

File: judges/quality-of-service/quality-of-service.rb [hunk 3]
```diff
@@ -32,15 +32,26 @@
...
+        mttr[workflow_id][:mttrs] ||= []
```
Comment (Yegorov) [inline judges/quality-of-service/quality-of-service.rb:42]: @Suban05 maybe we not needed nested constructions?
Isn't it easier to record a period of time in a regular array `mttrs` ?
And this line will no longer be needed  `mttrs = mttr.values.flat_map { |data| data[:mttrs] }.compact`

```ruby
mttrs = []
....

mttrs << (json[:updated_at] - mttr[workflow_id][:last_failed_at]).to_i
```

File: judges/quality-of-service/quality-of-service.rb [hunk 4]
```diff
@@ -32,15 +32,26 @@
   total = 0
   success = 0
   duration = 0
+  mttr = {}
   Fbe.unmask_repos.each do |repo|
     Fbe.octo.repository_workflow_runs(repo, created: ">#{f.since.utc.iso8601[0..9]}")[:workflow_runs].each do |json|
+      workflow_id = json[:workflow_id]
+      if json[:conclusion] == 'failure'
```
Comment (Yegorov) [inline judges/quality-of-service/quality-of-service.rb:39]: @Suban05 What if the status is `failure` several times in a row. E. g.:
| id | workflow_id | status  |
|----|-------------|---------|
| 1  | 1           | success |
| 2  | 1           | failure |
| 3  | 1           | failure |
| 4  | 1           | success |

`last_failed_at` - should be the first or last (id: 2 or 3 ) failure of workflow run?

File: judges/quality-of-service/quality-of-service.rb (hunk 1 above)
Comment (Yegorov) [reply judges/quality-of-service/quality-of-service.rb:40]:
```
{:id=>10564816841,
 :name=>"zerocracy",
 :node_id=>"WFR_kwLOL6J6Ss8AAAACdbZPyQ",
 :head_branch=>"master",
 :head_sha=>"42f96b41d866b73351ee87fdac920ac252cf2e00",
 :path=>".github/workflows/zerocracy.yml",
 :display_title=>"zerocracy",
 :run_number=>2798,
 :event=>"schedule",
 :status=>"completed",
 :conclusion=>"success",
 :workflow_id=>97829964,
 :check_suite_id=>27615969050,
 :check_suite_node_id=>"CS_kwDOL6J6Ss8AAAAGbgo_Gg",
 :url=>
  "https://api.github.com/repos/zerocracy/judges-action/actions/runs/10564816841",
 :html_url=>
  "https://github.com/zerocracy/judges-action/actions/runs/10564816841",
 :pull_requests=>[],
 :created_at=>2024-08-26 18:04:49 UTC,
 :updated_at=>2024-08-26 18:27:02 UTC,
:actor=>
  {:login=>"yegor256",
   :id=>526301,},
 :run_attempt=>1,
 :referenced_workflows=>[],
 :run_started_at=>2024-08-26 18:04:49 UTC,
```

Maybe we need use `run_started_at` field ? @yegor256 What do you think?

**Review by Yegorov — CHANGES_REQUESTED** [review]
@Suban05 There are several points

File: judges/quality-of-service/quality-of-service.rb (hunk 1 above)
Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb:40]: @Yegorov since there is no explicit field indicating the end time, I think `updated_at` indicates when the workflow has been completed. The `run_started_at` field indicates the launch date. We need the end date.

File: judges/quality-of-service/quality-of-service.rb (hunk 2 above)
Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb:41]: @Yegorov good suggestion, thanks

File: judges/quality-of-service/quality-of-service.rb (hunk 4 above)
Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb:39]: @Yegorov good point, thanks

Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb:40]: @Yegorov added changes and a test, take a look, please

Comment (Yegorov) [reply judges/quality-of-service/quality-of-service.rb:40]: @Suban05 Probably here we need the opinion of @yegor256 , we must rewrite failed time or leave the first failed time?
I think we must leave the first failed time.

Comment (tank-bohr) [reply judges/quality-of-service/quality-of-service.rb:40]: I believe we must take the first failure. MTTR means "mean time to repair."

File: judges/quality-of-service/quality-of-service.rb [hunk 5]
```diff
@@ -32,15 +32,25 @@
   total = 0
   success = 0
   duration = 0
+  mttrs = []
+  mttr = {}
```
Comment (tank-bohr) [inline judges/quality-of-service/quality-of-service.rb:36]: Naming could be improved. It's not supposed to have multiple mttr. MTTR is an average value of multiple time values. Thus, the name should be smth like `repair_times` or `ttrs` (times to repair)

File: judges/quality-of-service/quality-of-service.rb [hunk 6]
```diff
@@ -32,15 +32,25 @@
...
   Fbe.unmask_repos.each do |repo|
     Fbe.octo.repository_workflow_runs(repo, created: ">#{f.since.utc.iso8601[0..9]}")[:workflow_runs].each do |json|
```
[the remark this answers is not in the document]
Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb:38]: @tank-bohr probably, you're right. But I think it would be better to fix it through another pull request. Because this is beyond the scope of the current task.

**Comment by Suban05** [comment]
@Yegorov @tank-bohr updated

**Review by tank-bohr — APPROVED** [review]

File: judges/quality-of-service/quality-of-service.rb (hunk 1 above)
Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb]: @Yegorov I don't see where we can get the `duration` field...
what do you think about if we will check the `status` field and then can use `updated_at`? For example, if the status is completed then `updated_at` is end time

Comment (Yegorov) [reply judges/quality-of-service/quality-of-service.rb]: @Suban05 duration can be obtained for example:
```ruby
Fbe.octo.workflow_run_usage('zerocracy/judges-action', 10581095703)
```

Comment (Suban05) [reply judges/quality-of-service/quality-of-service.rb]: @Yegorov I got you, thanks!

**Comment by Suban05** [comment]
@Yegorov updated
tests fail, need this pr https://github.com/zerocracy/fbe/pull/84

File: judges/quality-of-service/quality-of-service.rb [hunk 7]
```diff
@@ -32,15 +32,27 @@
...
+  failed = {}
   Fbe.unmask_repos.each do |repo|
     Fbe.octo.repository_workflow_runs(repo, created: ">#{f.since.utc.iso8601[0..9]}")[:workflow_runs].each do |json|
+      workflow_id = json[:workflow_id]
+      run_duration = (Fbe.octo.workflow_run_usage(repo, json[:id])[:run_duration_ms] || 0) / 1000
+      completed = json[:run_started_at] + run_duration
+      if json[:conclusion] == 'failure' && failed[workflow_id].nil?
+        failed[workflow_id] = completed
+      elsif json[:conclusion] == 'success' && failed[workflow_id]
+        ttrs << (completed - failed[workflow_id]).to_i
```
Comment (Yegorov) [inline judges/quality-of-service/quality-of-service.rb:45]: @Suban05 `completed` var look as [redundant](https://www.yegor256.com/2015/09/01/redundant-variables-are-evil.html)
Look better as:
```ruby
ttrs << (json[:run_started_at] + run_duration - failed[workflow_id]).to_i
```

**Review by Yegorov — CHANGES_REQUESTED** [review]

**Review by Yegorov — APPROVED** [review]
@Suban05 Looks good!

**Comment by Suban05** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Suban05 thanks!

**Comment by 0crat** [comment]
@tank-bohr Hey there, awesome job on the review! 🎉 You've snagged +4 points, which is pretty cool considering all the factors that go into calculating these bonuses. Your total score is now sitting at a sweet [+137](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the great work, and remember, more detailed reviews with plenty of comments could boost your points even higher next time!

**Comment by 0crat** [comment]
@Yegorov Great job on the review! 🎉 You've earned +15 points: +4 base, +5 for reviewing 501 hits-of-code (capped at 16), and +5.5 for 22 comments (capped at 8). No deductions applied as you met all criteria. Your new balance is [+445](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the excellent work!

**Comment by 0crat** [comment]
@Suban05 Hey there, awesome job on your contribution! 👍 You've earned +4 points, which is our base reward. We had to deduct 8 points because your code was quite hefty (501 hits-of-code, over our 200 limit), and another 4 points due to the high number of review comments (23). But don't worry, we added 13 points to make sure you get something for your hard work. Your total balance is now [+565](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Remember, [quality over quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) is key. Keep those contributions coming, and aim for more concise, well-reviewed code next time!
