### PR TITLE
#543 fix "repository not found" when trying to add review comments bug Something isn't working

### LINKED ISSUE #543: "repository not found" when trying to add review comments
I see this in the [log](https://github.com/zerocracy/judges-action/actions/runs/14294248676/job/40059378242):

```
👉 Running add-review-comments (#0) at judges/add-review-comments/ (122ms already)...
Accessing GitHub API with a token (40 chars, ending by "W1Yf")
Set 0 review comments for PR #81 in repository 799177290
Set 0 review comments for PR #85 in repository 799177290
E: GET https://api.github.com/repositories/728758275 HTTP/1.1
     User-Agent: "Octokit Ruby Gem 9.2.0"
     Accept: "application/vnd.github.v3+json"
     Content-Type: "application/json"
     Authorization: "token ***"
   HTTP/1.1 404
     date: "Sun, 06 Apr 2025 16:05:33 GMT"
     content-type: "application/json; charset=utf-8"
     x-github-media-type: "github.v3; format=json"
     x-accepted-github-permissions: "metadata=read"
     x-github-api-version-selected: "2022-11-28"
     x-ratelimit-limit: "5000"
```

The repository is private, but it exists.

### PR DESCRIPTION
**Pull request by Suban05**
closes #543

### CODE REVIEW

**Comment by Suban05** [comment]
@yegor256 please check

File: judges/add-review-comments/add-review-comments.rb [hunk 1]
```diff
@@ -10,8 +10,13 @@
...
-    pl = Fbe.octo.pull_request(Fbe.octo.repo_name_by_id(f.repository), f.issue)
-    f.review_comments = pl[:review_comments]
-    $loog.info("Set #{pl[:review_comments]} review comments for PR ##{f.issue} in repository #{f.repository}")
+    begin
+      pl = Fbe.octo.pull_request(Fbe.octo.repo_name_by_id(f.repository), f.issue)
+      comments = pl[:review_comments]
+    rescue Octokit::NotFound
+      comments = 0
+    end
+    f.review_comments = comments
```
Comment (yegor256) [inline judges/add-review-comments/add-review-comments.rb:19]: @Suban05 that's a bad idea, since it's a lie. Instead, we should skip this fact, make no modifications to it.

**Review by yegor256 — CHANGES_REQUESTED** [review]
@Suban05 thanks! see above.

File: judges/add-review-comments/add-review-comments.rb (hunk 1 above)
Comment (Suban05) [reply judges/add-review-comments/add-review-comments.rb]: @yegor256 fixed

File: test/judges/test-add-review-comments.rb [hunk 2]
```diff
@@ -71,6 +71,26 @@ def test_adds_review_comments_to_facts_without_review_comments
...
+    what = 'pull-was-reviewed'
+    fb = Factbase.new
+    fact = fb.insert
+    fact.what = what
+    fact.issue = pl[:id]
+    fact.repository = repo
+    load_it('add-review-comments', fb)
+    facts = fb.query("(eq what \"#{what}\")").each.to_a
+    assert_equal(pl[:id], facts.first.issue)
+    assert_equal(
```
Comment (yegor256) [inline test/judges/test-add-review-comments.rb:88]: @Suban05 in general, it's a bad idea to assert on error messages. Instead, check for `facts.first['review_comments'].nil?`

File: test/judges/test-add-review-comments.rb [hunk 3]
```diff
@@ -71,6 +71,26 @@ def test_adds_review_comments_to_facts_without_review_comments
...
+    repo = 90
+    stub(repo, pl)
+    what = 'pull-was-reviewed'
+    fb = Factbase.new
+    fact = fb.insert
+    fact.what = what
+    fact.issue = pl[:id]
+    fact.repository = repo
+    load_it('add-review-comments', fb)
+    facts = fb.query("(eq what \"#{what}\")").each.to_a
```
Comment (yegor256) [inline test/judges/test-add-review-comments.rb:86]: @Suban05 you can use single quotes inside the query

**Review by yegor256 — CHANGES_REQUESTED** [review]
@Suban05 a few more suggestions above

**Comment by Suban05** [comment]
@yegor256 fixed, please check

**Comment by yegor256** [comment]
@Suban05 thanks!

**Comment by 0crat** [comment]
@Suban05 Thanks for your contribution! You've earned +4 points: +4 base, -16 for no code review, +16 to meet the minimum. While we appreciate your effort, remember that code reviews are crucial for quality and collaboration. Next time, aim for a review and consider adding more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) to boost your points. Let's focus on [balancing speed and quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in future contributions. Keep up the good work!
